AWSTemplateFormatVersion: "2010-09-09"

Description: >-
  Stack containing: DynamoDB

Parameters:
  ApplicationName:
    Type: String
    Default: "climapush-database"
  ApplicationDescription:
    Type: String
    Default: "climapush - Database"
  EnvironmentName:
    Type: String
    AllowedValues:
      - "dev"
      - "prod"

Conditions:
  IsDevEnvironment:
    !Equals [!Ref EnvironmentName, "dev"]

Resources:
  Database:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub "${EnvironmentName}-${ApplicationName}"
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: "PK"
          AttributeType: "S"
        - AttributeName: "SK"
          AttributeType: "S"
        - AttributeName: "GSI1PK"
          AttributeType: "S"
        - AttributeName: "GSI1SK"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "PK"
          KeyType: "HASH"
        - AttributeName: "SK"
          KeyType: "RANGE"
      GlobalSecondaryIndexes:
        - IndexName: "GSI1"
          KeySchema:
            - AttributeName: "GSI1PK"
              KeyType: "HASH"
            - AttributeName: "GSI1SK"
              KeyType: "RANGE"
          Projection:
            ProjectionType: "ALL"
      Tags:
        - Key: Application
          Value: !Ref ApplicationName
        - Key: Environment
          Value: !Ref EnvironmentName
        - Key: Tier
          Value: database
