version: '3.8'
services:
  dynamodb-climapush:
    command: "-jar DynamoDBLocal.jar"
    image: "amazon/dynamodb-local:latest"
    container_name: dynamodb-climapush
    ports:
      - "8000:8000"
    working_dir: /home/dynamodblocal

  gen-sonar:
    image: sonarqube:8.2-community
    container_name: sonar
    ports:
      - 9001:9000
      - 9092:9092
